[package]
name = "ps3decrs"
version = "2.0.1"
edition = "2024"
description = "PS3 ISO decryption tool."
repository = "https://github.com/Redrrx/ps3dec"
readme = "README.md"
license = "MIT"
keywords = ["ps3", "iso", "decryption", "bluray"]
categories = ["command-line-utilities", "cryptography"]
rust-version = "1.85"
include = ["src/**", "Cargo.toml", "README*", "LICENSE*"]


[dependencies]
clap = { version = "4.5.2", features = ["cargo"] }
aes = "0.8.4"
hex = "0.4.3"
indicatif = "0.18.0"
rayon = "1.9.0"
generic-array = "0.14.7"
log = "0.4"
fern = "0.7.1"
chrono = "0.4"
num_cpus = "1.17.0"

[profile.release]
opt-level = 3
strip = true
lto = "fat"

[build]
rustflags = ["-C", "target-cpu=native"]

[lib]
name = "ps3dec"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "ps3dec"
path = "src/main.rs"

